Dynatrace/dynatrace-otel-collector

- config_examples/README.md
Fixes a link in `config_examples/README.md` that linked `effective.yaml.yaml` instead of `effective.yaml`.
> docs: fix link in examples README

- config_examples/README.md
- config_examples/spanmetrics.yaml
- testbed/integration/config_examples_test.go
- testbed/integration/trace_validation.go
This configuration provides a basis for using the span metrics connector to obtain request call counts, error counts, and response time durations for traces that arrive at the Collector. These traces can also be sampled, which can be used to reduce total data ingest into Dynatrace.
cc @mviitane @mreider
> Provide example for deriving metrics from pre-sampled traces

- .goreleaser.yaml
Addresses issue where the collector fails to locate timezones when using the Syslog receiver
> Include `timetzdata` build flag

- .goreleaser.yaml
- manifest.yaml
Followup from #166, creating a hotfix on the already released v.0.3.0 version.
> hotfix Include `timetzdata` build flag 

- .chloggen/summary.tmpl
- CHANGELOG.md
- manifest.yaml
Since this is the first release with the new changelog process, we will have to manually add the things we did as there's no changelog entry files. We can grab those from the automated release notes GH generates once we create the tag and release.
> Prepare v0.6.0 changelog

- .chloggen/summary.tmpl
- CHANGELOG.md
Hand-picked items from the auto-generated release notes to the CHANGELOG.md. From now one, this will not be needed as we will be using the changelog tooling. 
I also modified the changelog template a bit, to match the upstream collector "style".
> Manually add items from the 0.6.0 release to changelog

- .markdown_link_check_config.json
Looks like we forgot to add the markdown-lint-check config file in #191 :slightly_smiling_face:
> chore: add markdown-link-check config

- .chloggen/feat_int-test-syslog.yaml
- config_examples/README.md
- config_examples/syslog.yaml
- internal/testbed/integration/config_examples_test.go
- internal/testbed/integration/data_providers.go
- internal/testbed/integration/syslog_logs_validation.go
- internal/testbed/integration/testutils.go
This PR adds the syslog ingest example from the [Dynatrace Documentation](https://docs.dynatrace.com/docs/extend-dynatrace/opentelemetry/collector/use-cases/syslog) as well as integration tests for it.
> test(examples/syslog): add test and example for syslog

- Makefile
- internal/testbed/integration/statsd/e2e_test.go
- internal/testbed/testdata/config-allcomponents.yaml
- fixes failing all-components test by adding missing statsd and zipkin receivers
- fixes statsd e2e test by adding the `//go build e2e` comment to add it to the correct CI run
- adapted Makefile to fail CI step when one of the test fails, but continue with execution of the rest of the tests, run [here](https://github.com/Dynatrace/dynatrace-otel-collector/actions/runs/10141462064/job/28038753215?pr=250)
> [chore]: fail testsuite when one of the tests fails

- internal/confmap/provider/eecprovider/provider.go
- internal/confmap/provider/eecprovider/provider_test.go
The EEC config provider was mistakenly sending `Api-Token: xxx` in the headers instead of `Authorization: Api-Token xxx`.
> fix(eecprovider): Fix authentication header format

- .chloggen/add-missing-dep.yaml
- .goreleaser.yaml
- docs/releasing.md
This PR synchronizes the distro linux packages with upstream updates from https://github.com/open-telemetry/opentelemetry-collector-releases/pull/617 and https://github.com/open-telemetry/opentelemetry-collector-releases/pull/620.
> fix: add missing dependency to sh for RPM linux packages

- .github/workflows/load-tests.yml
Load tests can still be triggered manually for feature branches, just the automatic running will be disabled.
> [chore] disable load tests on PRs to reduce runtime cost in the future

- README.md
see https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/troubleshooting.md
> [chore] Remove reference to deprecated upstream troubleshooting docs

- .github/workflows/e2e.yaml
- .github/workflows/load-tests.yml
This PR changes the runner for our load tests to our new github hosted larger runner with 16 core.
> [chore] use bigger runner for load tests

- internal/testbed/load/tests/metrics_test.go
This PR increases the load test resource limits slightly since test runs were failing a few times on main branch now with limits being slightly overshot in some cases.
> [chore] increase load test resource limits

- internal/testbed/load/tests/scenarios.go
This PR fixes the `dropped_span_count` metric reported in the benchmark results. 
The high number of dropped spans was reported because for the pull based scenario, the number of sent data items is the static number of metrics exposed via each prometheus endpoint (e.g. 1000), whereas the number of received items is the number of metrics times the number of performed scrape iterations due to the internal mechanics of the testbed validator's benchmark summary this is then recorded as "dropped_span_count".
The name "dropped_span_count" is also misleading here, as this is calculated from the number of generated data items minus the number of received items - which don't have to be spans in each case, but can also be metrics or logs.
> [chore] fix dropped data item counter

- .chloggen/summary.tmpl
Before that, the dynatrace distribution section was not added to the generated changelog if there have only been changes marked as enhancement since the previous release
> [chore] add check for enhancements in release notes template

- .github/workflows/changelog.yml
markdown-link-check has some issue in newer versions that's not fixed yet. (see https://github.com/tcort/markdown-link-check/issues/369)
This PR pins the version to last known working one: 3.12.2
> [chore] pin markdown-link-check version to last working one

- renovate.json
Tested on fork: https://github.com/odubajDT/dynatrace-otel-collector/pull/11/files
> [chore] remove deprecated regexMatcher from renovate config

- internal/testbed/load/tests/metrics_test.go
- internal/testbed/load/tests/trace_test.go
According to the recent results https://dynatrace.github.io/dynatrace-otel-collector/benchmarks/loadtests/ there was no significant or sudden increase in the memory consumption, but it was always rather close to the specified limits
> [chore] increase limits for load tests

- internal/testbed/load/tests/metrics_test.go
We saw a load test fail due to being a single Megabyte over the limit: https://github.com/Dynatrace/dynatrace-otel-collector/actions/runs/12300638511/attempts/1
I'm slightly bumping this slightly so the test is less flaky.
> [chore] Bump the expected max memory for Prometheus load test

- .chloggen/ppcle-s390x-arch-support.yaml
- .github/workflows/changelog.yml
- .github/workflows/release.yaml
- .github/workflows/snapshot.yaml
- .goreleaser.yaml
- README.md
- adds builds for ppc64le and s390x architectures
- adapts the support statement
- adds missing license OCI labels to container images
> Add builds for ppc64le and s390x architectures

- internal/testbed/integration/prometheus/e2e_test.go
The metrics exposed by the collector's self monitoring prometheus endpoint at port `8888` contain a `service_name="dynatrace-otel-collector"` label, which is used for the resulting  resource name.
Previously, apparently the job name from the prometheus config has been used for the service name:
```
- job_name: opentelemetry-collector
scrape_interval: 60s
static_configs:
- targets:
- 127.0.0.1:8888
```
I'm not 100% sure yet why this has changed with the new upstream release, but my guess is that this is linked to the recent major version upgrade of the prometheus dependency: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/36873
Update: It seems like since the prometheus version upgrade, the prometheus scrape manager will convert the `service_name` label provided by …
> [chore] fix expected service name for prometheus e2e test

- docs/dashboards/README.md
The config scheme upstream has been changed to v0.3 where the headers have to be provided as a list of key value pairs: https://github.com/open-telemetry/opentelemetry-collector/blob/58f3efbc35483c478d785ecea50a467ce1602707/service/telemetry/internal/migration/v0.3.0.go#L30
I noticed that If the headers are provided with the old scheme, parsing the config as v0.3 will fail, and v0.2 will be used as a fallback - the endpoint and authorization config will still be set in that case, however the `temporality_preference` will not be applied correctly in this case, leading many self monitoring metrics to be rejected by Dynatrace.
This PR fixes this by following the new scheme.
> [chore] fix the self monitoring config

- .chloggen/summary.tmpl
- .github/workflows/release.yaml
- Makefile
This PR populates the github releases notes with the generated changelog from chloggen removing a manual step to copy/paste the release notes into the github release.
> [chore] add previous tag to changelog template

- .github/workflows/check-links.yml
- .github/workflows/snapshot.yaml
- CONTRIBUTING.md
- docs/releasing.md
- lychee.toml
This PR adds lychee link scanning on PRs and on push to main for the complete repo.
It also runs the link checker every monday morning and will file an issue if broken links come up.
> [chore] add Lychee link scanning for the complete repo

- CHANGELOG.md
- internal/release/postinstall.sh
There was an upstream change in the [`postinstall.sh` script ](https://github.com/open-telemetry/opentelemetry-collector-releases/blob/v0.122.0/distributions/otelcol/postinstall.sh) that solves for situations where the script is run in a chroot and Systemd isn't running, even though it is used on the host system and the `systemctl` binary is available.
> [chore] Adapt Linux package script changes from v0.122.0

- .gitignore
Due to the recent change in generation of [chlog](https://github.com/Dynatrace/dynatrace-otel-collector/commit/373831d562febd94a0be32e7160277b87743cbaa), the generated file needs to be added to gitignore, as goreleaser is not able to do the release unless the git tree is clean
Failed release https://github.com/Dynatrace/dynatrace-otel-collector/actions/runs/13986624830/job/39161391053
> [chore] add generated release notes file to gitignore

- .github/workflows/release.yaml
- .github/workflows/snapshot.yaml
- .goreleaser.yaml
- renovate.json
- switch from SPDX to CycloneDX to align with publicly available SBOMs for Operator, ActiveGate and dynatrace-configuration-as-code
- use `cyclonedx-gomod` instead of `syft` for more accurate Go package detection, added license information and source repo information (if available)
- generate the SBOM for each binary and store it in a file that follows the existing naming convention for binaries, e.g., `dynatrace-otel-collector_0.0.1-next_Linux_x86_64-sbom.cdx.json`
Changes have been tested in a private fork. 
An example SBOM output can be found here -> [dynatrace-otel-collector_0.0.1-next_Linux_x86_64-sbom.cdx.json](https://github.com/user-attachments/files/19719433/dynatrace-otel-collector_0.0.1-next_Linux_x86_64-sbom.cdx.json).
> [chore] generate CycloneDX SBOM using `cyclonedx-gomod`

- CHANGELOG.md
Properly sets the version in the changelog to `v0.30.0`. The manifest version is already correct.
> [chore] Fix release version in changelog

- .github/workflows/release.yaml
- .github/workflows/snapshot.yaml
The release is [currently failing](https://github.com/Dynatrace/dynatrace-otel-collector/actions/runs/15069134936/job/42366937298) due to a lack of disk space. This should hopefully help free up some space.
> [chore] Free additional disk space on runners

- .chloggen/add-leader-elector.yaml
- README.md
- internal/testbed/testdata/config-allcomponents.yaml
- manifest.yaml
Testing of the extension will be part of the [k8s combined instegration test scenario](https://github.com/Dynatrace/dynatrace-otel-collector/pull/581)
> [extension/k8sleaderelector] Add extension to distribution

- renovate.json
This PR removes some regex in favor of using the built-in [renovate manager for OCB manifests](https://docs.renovatebot.com/modules/manager/ocb/).
> [chore] use built-in renovate manager for collector manifest

- renovate.json
This PR adapts the regex for detecting the ocb manifest. With these changes, the components in the manifest are updated again. Verified on a forked repo: https://github.com/bacherfl/dynatrace-otel-collector/pull/2
> [chore] change regex for ocb manifest
