README.md, config_examples/README.md, docs/releasing.md, manifest.yaml
Updates the name of the Distro across the repository.
=> docs: update name to 'Dynatrace distribution of the OpenTelemetry Collector'

manifest.yaml
In preparation for the next release.
=> Bump version to v0.4.0

renovate.json
The current config has a trailing comma that is parsable, but not valid JSON.
=> [chore] Update Renovate config

config_examples/README.md
This PR adds a message to the config_examples readme to make users aware of the change to localhost for all endpoints.
=> [chore] Add notice about localhost breaking change

CHANGELOG.md
=> [chore] Highlight breaking changes in CHANGELOG.md

.github/workflows/ci.yaml
Allow manually running CI on branches
=> [chore] Allow manually running CI on branches

.github/workflows/snapshot.yaml, .goreleaser.yaml, Makefile, internal/testbed/linux-services/Dockerfile.test.deb, internal/testbed/linux-services/Dockerfile.test.rpm, internal/testbed/linux-services/README.md, internal/testbed/linux-services/common.sh, internal/testbed/linux-services/config.test.yaml, internal/testbed/linux-services/package-tests.sh
- adds tests on amd64 for the linux packages (deb and rpm) using container images that are run with podman
- adds a readme for running the tests locally
- adds the tests to the already existing snapshot pipeline
=> [chore] add linux package tests

.github/workflows/snapshot.yaml, .goreleaser.yaml, Makefile, internal/testbed/linux-services/package-tests.sh
This PR adds linux package tests for arm64 .deb and .rpm packages using QEMU
=> [chore] enable ARM64 linux package tests

docs/benchmarks/loadtests/index.html
This PR takes the upstream index.html file with some slight addaptations and re-uses it.
How to test:
- download index.html
- download data.js from the same folder
- view locally in browser
=> [chore] update benchmark index file to fit data

.github/workflows/load-tests.yml
This PR adds a slack notification for when the load tests fail.
=> [chore] add slack webhook for failing load tests

.chloggen/filtering-iban.yaml, config_examples/masking_iban.yaml, config_examples/redaction_iban.yaml, internal/testbed/integration/filtering_test.go
- introduce example config to mask IBANs with transform processor
- introduce example config to redact IBANs with redaction processor
- introduce integration tests for both configs
=> Introduce masking and redaction example of international IBANs

.chloggen/fix-unit-file-docs-key.yaml, internal/release/dynatrace-otel-collector.service
=> fix: add service documentation key to correct unit section

.github/actions/create-cluster/action.yaml, .github/workflows/changelog.yml, .github/workflows/ci.yaml, .github/workflows/e2e.yaml, .github/workflows/load-tests.yml, .github/workflows/release.yaml, .github/workflows/snapshot.yaml, Makefile, renovate.json
- pin ubuntu runner version
- polish usage of golang version installation via env variable
- adapt renovate config to update dependencies which were not updated + enhance the config
Run visible [here](https://github.com/odubajDT/dynatrace-otel-collector/issues/2)
=> [chore] Adapt renovate config to update all repository dependencies

renovate.json
renovate PR on fork: https://github.com/odubajDT/dynatrace-otel-collector/pull/11/files
=> [chore] group OTel collector dependency updates into single PR

.github/workflows/changelog.yml
reverts https://github.com/Dynatrace/dynatrace-otel-collector/pull/388
=> [chore] revert MD link check version

internal/data-ingest-cli/README.md, internal/data-ingest-cli/commands/otlpjson/command.go, internal/data-ingest-cli/commands/statsd/command.go, internal/data-ingest-cli/commands/statsd/testdata/metrics.txt, internal/data-ingest-cli/go.mod, internal/data-ingest-cli/go.sum, internal/data-ingest-cli/main.go, internal/data-ingest-cli/receiver/common.go, internal/data-ingest-cli/receiver/otlp/otlp.go, internal/data-ingest-cli/receiver/otlphttp/otlphttp.go, internal/data-ingest-cli/sender/statsd/sender.go
This PR introduces a statsd sender to send statsd data into Collector as well as OTLP HTTP receiver to receive data from otlphttp exporter of the collector
=> [chore] enhance CLI tool to ingest statsd data to the collector

.goreleaser.yaml
Documented here:
* https://goreleaser.com/deprecations/#archivesformat
* https://goreleaser.com/deprecations/#archivesformat_overridesformat
* https://goreleaser.com/deprecations/#snapshotname_template
=> [chore] Handle GoReleaser config deprecations

config_examples/prometheus.yaml, internal/data-ingest-cli/README.md, internal/data-ingest-cli/commands/prometheus/command.go, internal/data-ingest-cli/commands/prometheus/config.yaml, internal/data-ingest-cli/commands/prometheus/testdata/metrics, internal/data-ingest-cli/main.go
Add a simple HTTP server that serves a payload with Prometheus metrics for testing Prometheus ingest in the Collector.
=> [chore] Add Prometheus server to ingest CLI

.github/workflows/security.yml
Snyk run: https://github.com/Dynatrace/dynatrace-otel-collector/actions/runs/13942143452/job/39021045490?pr=509
=> [chore] enable security checks only on pushes to main branch

.github/workflows/release.yaml, .github/workflows/snapshot.yaml, renovate.json
Since this was solved upstream already, I copied the renovate config for Goreleaser Pro downstream.
=> [chore] update renovate to work with goreleaser pro

renovate.json
Reduce renovate config for goreleaser pro and also fix it
=> [chore] fix renovate config
